# Generated by Django 5.2.11 on 2026-02-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню сайта', 'verbose_name_plural': 'Меню сайта'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order', 'title']},
        ),
    ]
